version: '3.8'
services:
  distrybute:
    image: ghcr.io/mmichaelb/distrybute:latest@sha256:ec85265adf861e5a96b36320b8c4630c5fbdba5e88b02096980c0d62bc29d800
    restart: unless-stopped
    ports:
      - "127.0.0.1:10711:10711"
    environment:
      DISTRYBUTE_LOG_FILE: /var/log/distrybute/log.json
      DISTRYBUTE_MINIO_ENDPOINT: minio:9000
      DISTRYBUTE_MINIO_ID: distrybute
      DISTRYBUTE_MINIO_SECRET: distrybute
      DISTRYBUTE_MINIO_BUCKET: distrybute
      DISTRYBUTE_POSTGRES_USER: distrybute
      DISTRYBUTE_POSTGRES_PASSWORD: distrybute
      DISTRYBUTE_POSTGRES_HOST: postgres
      DISTRYBUTE_POSTGRES_DB: distrybute
    volumes:
      - ./log:/var/log/distrybute/
    networks:
      - distrybute_compose
  postgres:
    image: postgres:14@sha256:742d81929714eac14b8f53e0e78ab3b9e2bee6740d7b39d6bc3b54ebb8398b50
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: distrybute
      POSTGRES_USER: distrybute
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql
    networks:
      - distrybute_compose
  minio:
    image: minio/minio:latest@sha256:03bd681f5661eddccafc11aaff284819b288d3514471e5bd055d79d85030cee4
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: distrybute
      MINIO_ROOT_PASSWORD: distrybute
    volumes:
      - ./minio:/data
    networks:
      - distrybute_compose
networks:
  distrybute_compose:
