version: '3.8'
services:
  postgres:
    image: postgres:14@sha256:9ceb24f8c5f15c053d973a3610866f473690875dc13eb3282b45302189321040
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    image: minio/minio:latest@sha256:a2fd67a22c9fea2943d44b9b8174a94663b2042390a9b0737ba6f808868d96ec
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "127.0.0.1:9000:9000"
