version: '3.8'
services:
  postgres:
    image: postgres:15@sha256:44ff1c71ec6b29232d51cfe15a86cd9827d9e254a95aa1f7a341299fc30261c5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    image: minio/minio:latest@sha256:ac727c1d3d54dda5dddb687f7304ece600237792e01a73d134e129e3c5c26dae
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "127.0.0.1:9000:9000"
