version: '3.8'
services:
  postgres:
    image: postgres:14@sha256:3e2eba0a6efbeb396e086c332c5a85be06997d2cf573d34794764625f405df4e
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    image: minio/minio:latest@sha256:5e299810b1dc8224e4e04304fd0032b7541713b06b18a8b8b7364c60d5d7848d
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "127.0.0.1:9000:9000"
