version: '3.8'
services:
  postgres:
    image: postgres:14@sha256:64ecb399c16daafe385a7d52077425d5fcc33e642b0a953f70d7c7c572624d0a
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    image: minio/minio:latest@sha256:ad4d151550f271380fd21587fe23fc4e4182d667dca30f61709b3d154a29d4c6
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "127.0.0.1:9000:9000"
