version: '3.8'
services:
  postgres:
    image: postgres:14@sha256:2481115cad236897774fa13fef07ceb0e5fdc0a75457a047c441aada670cdfaf
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    image: minio/minio:latest@sha256:6a125ee7860f387d4b1d9aface8be01413e2a9f803508d23b5e9dd64b833e7a7
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "127.0.0.1:9000:9000"
