version: '3.8'
services:
  postgres:
    image: postgres:15@sha256:a5e89e5f2679863bedef929c4a7ec5d1a2cb3c045f13b47680d86f8701144ed7
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    image: minio/minio:latest@sha256:a6f318a0b80d344553cee9acd979df480309f22b79390840e3b5c9f753c875d1
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "127.0.0.1:9000:9000"
