version: '3.8'
services:
  postgres:
    image: postgres:14@sha256:60b2f01c86f02f1d09f060caa36d0765a80a7a0656b6069c98fbb43791dfd33f
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    image: minio/minio:latest@sha256:8cef6dfd1108dacee4eff59f1b257151b13358d22db147b76db168cbe6f88661
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "127.0.0.1:9000:9000"
