version: '3.8'
services:
  postgres:
    image: postgres:14@sha256:befb4cdc1d944bd89784b9caa287cf025f0720f9a02436038124163accd177dc
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    image: minio/minio:latest@sha256:2482aa0635424b409dbee995e18c0f4bbc64e385fc4ea305b73c9b0c1388a6bd
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "127.0.0.1:9000:9000"
