version: '3.8'
services:
  postgres:
    image: postgres:14@sha256:117e7b9287612505575ac11db1cf81742eea6fd5cd8b2ce26e40f366b1f74e25
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distrybute
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    image: minio/minio:latest@sha256:cbcbaaab1c30b7013354b1c2eb72777fa88de7f64d9e258d7b762513f485a7e2
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "127.0.0.1:9000:9000"
