definitions:
  controller.FileUploadResponse:
    properties:
      callReference:
        type: string
    type: object
  controller.Response:
    properties:
      data: {}
      errorMessage:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
  description: API documentation for the REST API of distrybute, a lightweight image
    upload server.
  license:
    name: MIT
    url: https://github.com/mmichaelb/distrybute/blob/master/LICENSE
  title: distrybute API
  version: 0.0.1
paths:
  /api/file:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Contains the file content which should be uploaded
        in: formData
        name: file
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: The response which contains the callReference
          schema:
            allOf:
            - $ref: '#/definitions/controller.Response'
            - properties:
                data:
                  $ref: '#/definitions/controller.FileUploadResponse'
              type: object
      summary: Upload a file using a POST request.
  /v/{callReference}:
    get:
      consumes:
      - application/json
      operationId: uploadFile
      parameters:
      - description: Call Reference
        in: path
        name: callReference
        required: true
        type: integer
      produces:
      - application/octet-stream
      responses:
        "200":
          description: ""
      summary: Retrieve a file by using the callReference parameter.
swagger: "2.0"
