definitions:
  controller.FileUploadResponse:
    properties:
      callReference:
        type: string
      deleteReference:
        type: string
    type: object
  controller.Response:
    properties:
      data: {}
      errorMessage:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
  description: The basic auth token provided by distrybute and used to upload files.
  license:
    name: MIT
    url: https://github.com/mmichaelb/distrybute/blob/master/LICENSE
  title: distrybute API
  version: 0.0.1
paths:
  /api/file:
    post:
      consumes:
      - multipart/form-data
      operationId: uploadFile
      parameters:
      - description: Contains the file content which should be uploaded
        in: formData
        name: file
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: The response which contains the callReference
          schema:
            allOf:
            - $ref: '#/definitions/controller.Response'
            - properties:
                data:
                  $ref: '#/definitions/controller.FileUploadResponse'
              type: object
        default:
          description: ""
          schema:
            $ref: '#/definitions/controller.Response'
      security:
      - ApiKeyAuth: []
      summary: Upload a file using a POST request.
      tags:
      - files
  /api/file/delete/{deleteReference}:
    get:
      operationId: deleteFile
      parameters:
      - description: Call Reference
        in: path
        name: deleteReference
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controller.Response'
      summary: Deletes a specific file using the provided delete reference.
      tags:
      - files
  /v/{callReference}:
    get:
      operationId: retrieveFile
      parameters:
      - description: Call Reference
        in: path
        name: callReference
        required: true
        type: integer
      produces:
      - application/octet-stream
      - application/json
      responses:
        "200":
          description: ""
        default:
          description: ""
          schema:
            $ref: '#/definitions/controller.Response'
      summary: Retrieve a file by using the callReference parameter.
      tags:
      - files
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
