name: "[cli] Build, deploy"
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.x
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Build code
        run: make build-cli
  docker-build:
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker image
        run: |
          make docker-build-cli
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: mmichaelb
          password: ${{ secrets.DOCKERHUB_SECRET }}
        if: ${{ github.ref_type == 'tag' }}
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
        if: ${{ github.ref_type == 'tag' }}
      - name: Build and push cross-platform images
        run: |
          make docker-cross-platform-buildx-push-cli
        if: ${{ github.ref_type == 'tag' }}
