name: Integration tests (Postgres & Minio)
on:
  push:
  pull_request:
env:
  DISTRYBUTE_TEST_DB: ${{ format('distrybute_{0}', github.run_id) }}
  MINIO_TEST_BUCKET_NAME: ${{ format('distrybute-{0}', github.run_id) }}
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ${{ env.DISTRYBUTE_TEST_DB }}
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      minio:
        image: fclairamb/minio-github-actions
        ports:
          - 9000/tcp
        options: >-
          --health-cmd "curl http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test code
        run: make postgres-minio-integration-test
        env:
          TEST_POSTGRES_HOST: localhost
          TEST_POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          TEST_POSTGRES_DB: ${{ env.DISTRYBUTE_TEST_DB }}
          TEST_MINIO_HOST: localhost
          TEST_MINIO_PORT: ${{ job.services.minio.ports[9000] }}
          TEST_MINIO_BUCKET_NAME: ${{ env.MINIO_TEST_BUCKET_NAME }}
